apiVersion: v2
name: procare-sync
description: Procare Online data sync service
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: mysql
    version: "11.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
