apiVersion: v1
kind: Secret
metadata:
  name: {{ include "procare-sync.fullname" . }}
  labels:
    {{- include "procare-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  PROCARE_AUTH_TOKEN: {{ .Values.procare.authToken | quote }}
  PROCARE_EMAIL: {{ .Values.procare.email | quote }}
  PROCARE_PASSWORD: {{ .Values.procare.password | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
